-- AlterEnum
ALTER TYPE "SosStatus" ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE "SosStatus" ADD VALUE IF NOT EXISTS 'ACKNOWLEDGED';
ALTER TYPE "SosStatus" ADD VALUE IF NOT EXISTS 'ESCALATED';
ALTER TYPE "SosStatus" ADD VALUE IF NOT EXISTS 'RESOLVED';
ALTER TYPE "SosStatus" ADD VALUE IF NOT EXISTS 'FALSE_ALARM';
